version: "3.8"
services:
  node-app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ilkin
      - MONGO_INITDB_ROOT_PASSWORD=ilkin123456
    volumes:
      - mongo_db:/data/db
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  mongo_db:
  redis_data:
